config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'sessions/create'

  get 'sessions/destroy'

  resources :webcomics
  get 'welcome/index'
  get '/about', to: 'welcome#about'

  root 'webcomics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include devise modules
  devise :omniauthable, :timeoutable, omniauth_providers: [:google]

  def self.from_omniauth(access_token)
    data = access_token.info
    User.find_by(email: data['email'])
  end

end

app/models/webcomic.rb
# == Schema Information
#
# Table name: webcomics
#
#  id            :integer          not null, primary key
#  author        :string           not null
#  title         :text             not null
#  medium        :string
#  width         :integer
#  height        :integer
#  creation_date :date
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  comic_image   :string
#

class Webcomic < ApplicationRecord
  mount_uploader :comic_image, ComicImageUploader
  validates :title, presence: true
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def google
    @user = User.from_omniauth(request.env['omniauth.auth'])

    # Users must be manually created in the database
    failure unless @user && @user.persisted?

    flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
    sign_in_and_redirect @user, event: :authentication
  end

  def failure
    flash[:error] = 'Authentication failed.'
    redirect_to root_path
  end

end

app/controllers/webcomics_controller.rb
class WebcomicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_webcomic, only: [:show, :edit, :update, :destroy]

  # GET /webcomics
  def index
    webcomics = Webcomic.all
    redirect_to webcomic_path(webcomics.last) unless webcomics.empty?
  end

  # GET /webcomics/1
  def show
  end

  # GET /webcomics/new
  def new
    @webcomic = Webcomic.new
  end

  # GET /webcomics/1/edit
  def edit
  end

  # POST /webcomics
  def create
    @webcomic = Webcomic.new(webcomic_params)

    if @webcomic.save
      redirect_to @webcomic, notice: 'Webcomic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /webcomics/1
  def update
    if @webcomic.update(webcomic_params)
      redirect_to @webcomic, notice: 'Webcomic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /webcomics/1
  def destroy
    @webcomic.destroy
    redirect_to webcomics_url, notice: 'Webcomic was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_webcomic
    @webcomic = Webcomic.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def webcomic_params
    params.fetch(:webcomic, {}).permit(:title, :author, :comic_image, :creation_date,
                                       :height, :width, :medium)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # TODO these flash messages probably return incorrect values, unless we decide to use patternfly
  def flash_message_alert_class(name)
    case name
    when "success"
      "success"
    when "warning"
      "warning"
    when "error"
      "danger"
    else
      "info"
    end
  end

  def flash_message_icon_class(name)
    case name
    when "success"
      "ok"
    when "warning"
      "warning-triangle-o"
    when "error"
      "error-circle-o"
    else
      "info"
    end
  end
end

app/helpers/webcomics_helper.rb
module WebcomicsHelper

  def random_webcomic_path
    webcomic_path(Webcomic.all.sample)
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
    <% flash.each do |name, msg| %>
        <%# TODO: This all assumes we use patternfly, which we probably won't. Need to come up with our own. %>
        <div class="col-sm-12">
          <div class="alert alert-<%= flash_message_alert_class(name) %> alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
              <span class="pficon pficon-close"></span>
            </button>
            <span class="pficon pficon-<%= flash_message_icon_class(name) %>"></span> <%= msg %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-md navbar-light transparent">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="mb-5 collapse navbar-collapse justify-content-around" id="navbarSupportedContent">
      <ul class="navbar-nav justify-content-center">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link', id: 'webcomics-nav-item' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Webcomics', webcomics_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : 'Webcomics' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= content_for?(:body_class) ? yield(:body_class) : '' %>">
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash' unless local_assigns[:hide_flash] %>
  <div class="container">
    <%= yield %>
  </div>
  <%= content_for?(:javascript) ? yield(:javascript) : '' %>
  </body>
</html>

app/views/webcomics/_form.html.erb
<%= form_with(model: webcomic, local: true) do |form| %>
  <% if webcomic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webcomic.errors.count, "error") %> prohibited this webcomic from being saved:</h2>

      <ul>
      <% webcomic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" %>
    <%= form.label 'Title'  %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= form.label 'Author'  %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= form.label 'Medium'  %>
    <%= form.text_field :medium, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= form.label 'Creation Date'  %>
    <%= form.date_field :creation_date, value: Date.today.to_s, class: 'form-control' %>
  </div>

  <div class="form-group" %>
    <%= form.label 'Upload file'  %>
    <%= form.file_field :comic_image, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', webcomics_path, class: 'btn btn-secondary' %>
  </div>

<% end %>

app/views/webcomics/edit.html.erb
<h1>Editing "<%= @webcomic.title.capitalize %>"</h1>

<%= render 'form', webcomic: @webcomic %>

app/views/webcomics/index.html.erb
<div class="row justify-content-center">
  <div class="col col-sm-auto">
    <h1 class="animated swing">Nothings here yet!</h1>
  </div>
</div>

<br>

<%= link_to 'New Webcomic', new_webcomic_path, class: 'btn btn-primary' if user_signed_in? %>

app/views/webcomics/new.html.erb
<h1>Add a Webcomic</h1>

<%= render 'form', webcomic: @webcomic %>

app/views/webcomics/show.html.erb
<div class="row justify-content-center">
  <div class="col col-sm-auto">
    <h2><%= @webcomic.title.capitalize %></h2>
  </div>
</div>

<div class="row mt-5 mb-2 justify-content-center">
  <div class="col col-sm-auto">
    <%= image_tag @webcomic.comic_image.url %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col col-sm-auto">
    <%= link_to 'First', webcomic_path(Webcomic.first) %> |
    <%= link_to 'Back', '#' %> |
    <%= link_to 'Random', random_webcomic_path %> |
    <%= link_to 'Next', '#' %> |
    <%= link_to 'Latest', webcomic_path(Webcomic.last) %>
  </div>
</div>

<div class="row mt-5 justify-content-center">
  <div class="col col-sm-auto">
    <%= link_to 'New Webcomic', new_webcomic_path, class: 'btn btn-primary' if user_signed_in? %>
    <%= link_to 'Edit', edit_webcomic_path(@webcomic), class: 'btn btn-primary' if user_signed_in? %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="row justify-content-center">
  <div class="col col-sm-auto">
    <h2>About Us</h2>
  </div>
</div>
<% unless user_signed_in? %>
  <%= link_to 'Sign in with Google', user_google_omniauth_authorize_path, class: 'btn btn-info' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>